language: csharp
mono: none
dotnet: 3.1
solution: CompactCryptoGroupAlgebra.sln

before_install:
  - export COMMITTER_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty='%cE')"
  - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty='%aN')"
install:
  - dotnet restore
  - dotnet tool install coveralls.net --version 2.0.0 --framework netcoreapp3.1 --tool-path testPackages
script:
  - dotnet test CompactCryptoGroupAlgebra.Tests --logger "trx;LogFileName=TestResults.trx" --logger "nunit;LogFileName=TestResults.xml" --results-directory ./CompactCryptoGroupAlgebra.Tests/Coverage /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./Coverage/ /p:Exclude="[nunit.*]*"
  - dotnet test CompactCryptoGroupAlgebra.OpenSsl.Tests --logger "trx;LogFileName=TestResults.trx" --logger "nunit;LogFileName=TestResults.xml" --results-directory ./CompactCryptoGroupAlgebra.OpenSsl.Tests/Coverage /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./Coverage/ /p:Exclude=\"[nunit.*]*,[CompactCryptoGroupAlgebra]*,[CompactCryptoGroupAlgebra.Tests]*\" /p:Include="CompactCryptoGroupAlgebra.OpenSsl*"
after_success:
  - testPackages/csmacnz.Coveralls --multiple -i "opencover=CompactCryptoGroupAlgebra.Tests/Coverage/coverage.netcoreapp3.1.opencover.xml;opencover=CompactCryptoGroupAlgebra.OpenSsl.Tests/Coverage/coverage.netcoreapp3.1.opencover.xml" --serviceName travis-ci --jobId $TRAVIS_JOB_ID --commitId $TRAVIS_COMMIT --commitBranch $TRAVIS_BRANCH --commitAuthor "$AUTHOR_NAME" --commitEmail "$COMMITTER_EMAIL" --commitMessage "$TRAVIS_COMMIT_MESSAGE" --pullRequest $TRAVIS_PULL_REQUEST
