language: csharp
mono: latest
solution: CompactEC.sln
install:
  - nuget restore CompactEC.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release CompactEC.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./CompactEC.Tests/bin/Release/CompactEC.Tests.dll
